--NAir DEFINES
NDefines.NAir.BIGGEST_AGILITY_FACTOR_DIFF = 4.2 --Vanilla 4.0
NDefines.NAir.COMBAT_BETTER_AGILITY_DAMAGE_REDUCTION = 0.5 --Vanilla 0.45

NDefines.NAir.ANTI_AIR_PLANE_DAMAGE_FACTOR = 0.5
NDefines.NAir.ANTI_AIR_ATTACK_TO_DAMAGE_REDUCTION_FACTOR = 1.0
NDefines.NAir.ANTI_AIR_MAXIMUM_DAMAGE_REDUCTION_FACTOR = 0.70
NDefines.NAir.CAS_NIGHT_ATTACK_FACTOR = 0.5

NDefines.NAir.COMBAT_MULTIPLANE_CAP = 1.5			-- VANILLA 3
NDefines.NAir.AIR_REGION_SUPERIORITY_PIXEL_SCALE = 0.03
NDefines.NAir.COMBAT_DAMAGE_SCALE = 1.2
NDefines.NAir.COMBAT_DAMAGE_SCALE_CARRIER = 5
NDefines.NAir.DETECT_CHANCE_FROM_OCCUPATION = 0
NDefines.NAir.DETECT_EFFICIENCY_BASE = 0.5 --Vanilla 0.1
--NDefines.NAir.STRATEGIC_BOMBER_NUKE_AIR_SUPERIORITY = 0
NDefines.NAir.AIR_DEPLOYMENT_DAYS = 0
NDefines.NAir.AIR_WING_FLIGHT_SPEED_MULT = 0.2
NDefines.NAir.AIR_WING_XP_TRAINING_MISSION_GAIN_DAILY = 4.5
NDefines.NAir.CARRIER_PLANES_AMOUNT_FOR_POSITIONING = 50
NDefines.NAir.BASE_STRATEGIC_BOMBING_HIT_PLANE_CHANCE = 0.10	-- Chance to hit a plane in airbase when it is bombed. Vanilla 0.5
NDefines.NAir.ACE_WING_SIZE = 20	--size of wing ace bonuses are set up for. if lower more bonus, if higher less bonus. Vanilla 100

NDefines.NAir.AIR_MORE_GROUND_CREWS_COST = 0.0
NDefines.NAir.AIR_MORE_GROUND_CREWS_BOOST = 0.0

NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_TRUCK_DAMAGE_FACTOR = 0.054 --Vanilla 0.27
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_TRAIN_DAMAGE_FACTOR = 0.008 --Vanilla 0.040
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_RAILWAY_DAMAGE_SPILL_FACTOR = 0.0006 --Vanilla 0.006
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_DISRUPTION_MIN_DAMAGE_FACTOR = 0 --Vanilla 0.1
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_DIRECT_DISRUPTION_DAMAGE_FACTOR = 0 --Vanilla 0.01
NDefines.NAir.SECONDARY_DAMAGE_STRAT = 0.05 --Vanilla 0.2, how much damage gets translated to railway guns for strat bombing
NDefines.NAir.SECONDARY_DAMAGE_LOGISTICS = 0.25 --Vanilla 1, how much damage gets translated to railway guns for logistic strike
